// <auto-generated />
using System;
using BerberYonetimSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BerberYonetimSistemi.Migrations
{
    [DbContext(typeof(BerberDbContext))]
    [Migration("20251215233207_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BerberYonetimSistemi.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Berber", b =>
                {
                    b.Property<int>("BerberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BerberId"));

                    b.Property<string>("BerberAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ToplamKazanc")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BerberId");

                    b.ToTable("Berberler");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Calisan", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalisanId"));

                    b.Property<int?>("BerberId")
                        .HasColumnType("int");

                    b.Property<string>("CalisanAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("CalisanBaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("CalisanBitisSaati")
                        .HasColumnType("time");

                    b.Property<string>("CalisanSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalisanTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("CalisanId");

                    b.HasIndex("BerberId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Calisanlar");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Islem", b =>
                {
                    b.Property<int>("IslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemId"));

                    b.Property<string>("IslemAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IslemFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UzmanlikAlaniId")
                        .HasColumnType("int");

                    b.HasKey("IslemId");

                    b.HasIndex("UzmanlikAlaniId");

                    b.ToTable("Islemler");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciRolu")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSifreTekrar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuId"));

                    b.Property<DateTime?>("BaslangicSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("BerberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BitisSaati")
                        .HasColumnType("datetime2");

                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("IslemId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("RandevuSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("RandevuTarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RandevuUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SecilenIslemler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RandevuId");

                    b.HasIndex("BerberId");

                    b.HasIndex("CalisanId");

                    b.HasIndex("IslemId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.UzmanlikAlani", b =>
                {
                    b.Property<int>("UzmanlikAlaniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzmanlikAlaniId"));

                    b.Property<string>("UzmanlikAlaniAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UzmanlikAlaniId");

                    b.ToTable("UzmanlikAlanlari");
                });

            modelBuilder.Entity("CalisanUzmanlikAlani", b =>
                {
                    b.Property<int>("CalisanId")
                        .HasColumnType("int");

                    b.Property<int>("UzmanlikAlaniId")
                        .HasColumnType("int");

                    b.HasKey("CalisanId", "UzmanlikAlaniId");

                    b.HasIndex("UzmanlikAlaniId");

                    b.ToTable("CalisanUzmanlikAlani");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Calisan", b =>
                {
                    b.HasOne("BerberYonetimSistemi.Models.Berber", "Berber")
                        .WithMany("Calisanlar")
                        .HasForeignKey("BerberId");

                    b.HasOne("BerberYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany("Calisanlar")
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Berber");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Islem", b =>
                {
                    b.HasOne("BerberYonetimSistemi.Models.UzmanlikAlani", "UzmanlikAlani")
                        .WithMany("Islemler")
                        .HasForeignKey("UzmanlikAlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UzmanlikAlani");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Randevu", b =>
                {
                    b.HasOne("BerberYonetimSistemi.Models.Berber", "Berber")
                        .WithMany()
                        .HasForeignKey("BerberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerberYonetimSistemi.Models.Calisan", "Calisan")
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerberYonetimSistemi.Models.Islem", "Islem")
                        .WithMany("Randevular")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerberYonetimSistemi.Models.Kullanici", "Kullanici")
                        .WithMany("Randevular")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Berber");

                    b.Navigation("Calisan");

                    b.Navigation("Islem");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("CalisanUzmanlikAlani", b =>
                {
                    b.HasOne("BerberYonetimSistemi.Models.Calisan", null)
                        .WithMany()
                        .HasForeignKey("CalisanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BerberYonetimSistemi.Models.UzmanlikAlani", null)
                        .WithMany()
                        .HasForeignKey("UzmanlikAlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Berber", b =>
                {
                    b.Navigation("Calisanlar");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Islem", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.Kullanici", b =>
                {
                    b.Navigation("Calisanlar");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("BerberYonetimSistemi.Models.UzmanlikAlani", b =>
                {
                    b.Navigation("Islemler");
                });
#pragma warning restore 612, 618
        }
    }
}
